### ISSUE TITLE
Clover and Shadow. Possible to use together?

### ISSUE THREAD

**Issue by Favorlock** [bmuschko/gradle-clover-plugin#107]
I'm having trouble getting the clover plugin to play nice with the shadow plugin. I can build the project just fine so long as I'm not generating a clover report, but if I attempt to generate a clover report the gradle build fails due to compile time errors because it cannot find the shadow dependency classes. This appears to happen immediately after instrumentation according to the build log. Would really appreciate any nudges in the right direction assuming that it's even possible to use clover with shadow.

From what I can see the issue happens during the test task. I have added the stack trace to this issue.

Continued digging around and ended up adding the following to the build script. This solved the compile issues, although it appears that the report is reporting on the test classes rather than the source classes.

```
configurations.getByName("clover").extendsFrom(configurations.shadow)
```

Ok, so I figured out why, I didn't realize the tests should be in the same package. A bit of a derp on my part. So the above addition to the gradle script did resolve the issue, and making sure the application code and test code are in the same package solved the weirdness I was seeing in the reports. So altogether I think that solves this problem.

Gradle Script
```
buildscript {
    repositories {
        jcenter()
        mavenCentral()
        maven { url 'https://plugins.gradle.org/m2/' }
    }
}

plugins {
    id 'com.github.johnrengelman.shadow' version '1.2.4'
    id 'com.bmuschko.clover' version '2.2.0'
}

apply from: 'gradle/util.gradle'

subprojects {
    apply plugin: 'eclipse'
    apply plugin: 'idea'
    apply plugin: 'java'
    apply plugin: 'maven'
    apply plugin: 'com.github.johnrengelman.shadow'
    apply plugin: 'com.bmuschko.clover'

    apply from: scriptFile('deps.gradle')

    group 'com.enjin.minecraft_commons'
    version '0.0.1-SNAPSHOT'

    idea {
        module {
            scopes.PROVIDED.plus += [configurations.shadow]
        }
    }

    tasks.build.dependsOn(shadowJar)
    artifacts.archives shadowJar

    tasks.withType(AbstractCompile) {
        classpath += configurations.shadow
    }

    repositories {
        mavenLocal()
        mavenCentral()
        maven { url 'https://oss.sonatype.org/content/groups/public/' }
    }

    dependencies {
        shadow deps.javaCommons

        testCompile deps.junit
        testCompile deps.mockito
        testCompile deps.assertj

        clover deps.clover
    }

    jar {
        archiveName = "${project.name}-slim.jar"
    }

    shadowJar {
        archiveName = "${project.name}.jar"
    }

    clover {
        report {
            html = true
            pdf = true
        }
    }
}
```

Build Log:
```
11:39:28 PM: Executing tasks 'clean install cloverGenerateReport'...

:spigot:clean
:core:compileJava UP-TO-DATE
:core:processResources NO-SOURCE
:core:classes UP-TO-DATE
:core:jar UP-TO-DATE
:spigot:compileJava
:spigot:processResources NO-SOURCE
:spigot:classes
:spigot:jar
:spigot:shadowJar
:spigot:install
:spigot:compileTestJava
:spigot:processTestResources NO-SOURCE
:spigot:testClasses
:spigot:test
[clover-clean] OpenClover Version 4.2.0, built on April 30 2017 (build-1000)
[clover-clean] Loaded from: H:\Development\Data\Gradle\caches\modules-2\files-2.1\org.openclover\clover\4.2.0\6e24ca61354259476c48022595355dfe022e46ca\clover-4.2.0.jar
[clover-clean] Clover free edition.
[clover-setup] OpenClover Version 4.2.0, built on April 30 2017 (build-1000)
[clover-setup] Loaded from: H:\Development\Data\Gradle\caches\modules-2\files-2.1\org.openclover\clover\4.2.0\6e24ca61354259476c48022595355dfe022e46ca\clover-4.2.0.jar
[clover-setup] Clover free edition.
[clover-setup] Clover is enabled with initstring 'H:\Development\Workspaces\Enjin\enjin-minecraft-commons\spigot\build/.clover/clover.db-test'
    [javac] : warning: 'includeantruntime' was not set, defaulting to build.sysclasspath=last; set to false for repeatable builds
    [javac] Compiling 1 source file to H:\Development\Workspaces\Enjin\enjin-minecraft-commons\spigot\build\classes\java\main
   [clover] OpenClover Version 4.2.0, built on April 30 2017 (build-1000)
   [clover] Loaded from: H:\Development\Data\Gradle\caches\modules-2\files-2.1\org.openclover\clover\4.2.0\6e24ca61354259476c48022595355dfe022e46ca\clover-4.2.0.jar
   [clover] Clover free edition.
   [clover] Creating new database at 'H:\Development\Workspaces\Enjin\enjin-minecraft-commons\spigot\build\.clover\clover.db-test'.
   [clover] Processing files at 1.8 source level.
   [clover] Clover all over. Instrumented 1 file (1 package).
   [clover] Elapsed time = 0.027 secs. (37.037 files/sec, 1,000 srclines/sec)
    [javac] C:\Users\evanl\AppData\Local\Temp\clover6297908727183920210.tmp\com\enjin\minecraft_commons\spigot\command\SpigotCommandCallerType.java:3: error: package com.enjin.java_commons does not exist
    [javac] import com.enjin.java_commons.ObjectUtils;
    [javac]                              ^
    [javac] C:\Users\evanl\AppData\Local\Temp\clover6297908727183920210.tmp\com\enjin\minecraft_commons\spigot\command\SpigotCommandCallerType.java:5: error: package org.bukkit.command does not exist
    [javac] import org.bukkit.command.CommandSender;
    [javac]                          ^
    [javac] C:\Users\evanl\AppData\Local\Temp\clover6297908727183920210.tmp\com\enjin\minecraft_commons\spigot\command\SpigotCommandCallerType.java:7: error: cannot find symbol
    [javac] public class SpigotCommandCallerType implements CommandCallerType<CommandSender> {public static class __CLR4_2_000jdfmfth8{public static com_atlassian_clover.CoverageRecorder R;public static com_atlassian_clover.CloverProfile[] profiles = { };@java.lang.SuppressWarnings("unchecked") public static <I, T extends I> I lambdaInc(final int i,final T l,final int si){java.lang.reflect.InvocationHandler h=new java.lang.reflect.InvocationHandler(){public java.lang.Object invoke(java.lang.Object p,java.lang.reflect.Method m,java.lang.Object[] a) throws Throwable{R.inc(i);R.inc(si);try{return m.invoke(l,a);}catch(java.lang.reflect.InvocationTargetException e){throw e.getCause()!=null?e.getCause():new RuntimeException("Clover failed to invoke instrumented lambda",e);}}};return (I)java.lang.reflect.Proxy.newProxyInstance(l.getClass().getClassLoader(),l.getClass().getInterfaces(),h);}static{com_atlassian_clover.CoverageRecorder _R=null;try{com_atlassian_clover.CloverVersionInfo.An_old_version_of_clover_is_on_your_compilation_classpath___Please_remove___Required_version_is___4_2_0();if(20170430005756651L!=com_atlassian_clover.CloverVersionInfo.getBuildStamp()){com_atlassian_clover.Clover.l("[CLOVER] WARNING: The Clover version used in instrumentation does not match the runtime version. You need to run instrumented classes against the same version of Clover that you instrumented with.");com_atlassian_clover.Clover.l("[CLOVER] WARNING: Instr=4.2.0#20170430005756651,Runtime="+com_atlassian_clover.CloverVersionInfo.getReleaseNum()+"#"+com_atlassian_clover.CloverVersionInfo.getBuildStamp());}R=com_atlassian_clover.Clover.getNullRecorder();_R=com_atlassian_clover.Clover.getNullRecorder();_R=com_atlassian_clover.Clover.getRecorder("\u0048\u003a\u005c\u005c\u0044\u0065\u0076\u0065\u006c\u006f\u0070\u006d\u0065\u006e\u0074\u005c\u005c\u0057\u006f\u0072\u006b\u0073\u0070\u0061\u0063\u0065\u0073\u005c\u005c\u0045\u006e\u006a\u0069\u006e\u005c\u005c\u0065\u006e\u006a\u0069\u006e\u002d\u006d\u0069\u006e\u0065\u0063\u0072\u0061\u0066\u0074\u002d\u0063\u006f\u006d\u006d\u006f\u006e\u0073\u005c\u005c\u0073\u0070\u0069\u0067\u006f\u0074\u005c\u005c\u0062\u0075\u0069\u006c\u0064\u002f\u002e\u0063\u006c\u006f\u0076\u0065\u0072\u002f\u0063\u006c\u006f\u0076\u0065\u0072\u002e\u0064\u0062\u002d\u0074\u0065\u0073\u0074",1518161970421L,1000L,10,profiles,new java.lang.String[]{"clover.distributed.coverage",null});}catch(java.lang.SecurityException e){java.lang.System.err.println("[CLOVER] FATAL ERROR: Clover could not be initialised because it has insufficient security privileges. Please consult the Clover documentation on the security policy file changes required. ("+e.getClass()+":"+e.getMessage()+")");}catch(java.lang.NoClassDefFoundError e){java.lang.System.err.println("[CLOVER] FATAL ERROR: Clover could not be initialised. Are you sure you have Clover in the runtime classpath? ("+e.getClass()+":"+e.getMessage()+")");}catch(java.lang.Throwable t){java.lang.System.err.println("[CLOVER] FATAL ERROR: Clover could not be initialised because of an unexpected error. ("+t.getClass()+":"+t.getMessage()+")");}R=_R;}}public static final com_atlassian_clover.TestNameSniffer __CLR4_2_0_TEST_NAME_SNIFFER=com_atlassian_clover.TestNameSniffer.NULL_INSTANCE;
    [javac]                                                                   ^
    [javac]   symbol: class CommandSender
    [javac] C:\Users\evanl\AppData\Local\Temp\clover6297908727183920210.tmp\com\enjin\minecraft_commons\spigot\command\SpigotCommandCallerType.java:9: error: cannot find symbol
    [javac]     private Class<? extends CommandSender> rawType;
    [javac]                             ^
    [javac]   symbol:   class CommandSender
    [javac]   location: class SpigotCommandCallerType
    [javac] C:\Users\evanl\AppData\Local\Temp\clover6297908727183920210.tmp\com\enjin\minecraft_commons\spigot\command\SpigotCommandCallerType.java:11: error: cannot find symbol
    [javac]     public SpigotCommandCallerType(Class<? extends CommandSender> rawType) {__CLR4_2_000jdfmfth8.R.inc(0);
    [javac]                                                    ^
    [javac]   symbol:   class CommandSender
    [javac]   location: class SpigotCommandCallerType
    [javac] C:\Users\evanl\AppData\Local\Temp\clover6297908727183920210.tmp\com\enjin\minecraft_commons\spigot\command\SpigotCommandCallerType.java:18: error: cannot find symbol
    [javac]     public Class<? extends CommandSender> getRawType() {__CLR4_2_000jdfmfth8.R.inc(6);
    [javac]                            ^
    [javac]   symbol:   class CommandSender
    [javac]   location: class SpigotCommandCallerType
    [javac] C:\Users\evanl\AppData\Local\Temp\clover6297908727183920210.tmp\com\enjin\minecraft_commons\spigot\command\SpigotCommandCallerType.java:23: error: cannot find symbol
    [javac]     public boolean compare(CommandSender caller) {__CLR4_2_000jdfmfth8.R.inc(8);
    [javac]                            ^
    [javac]   symbol:   class CommandSender
    [javac]   location: class SpigotCommandCallerType
    [javac] C:\Users\evanl\AppData\Local\Temp\clover6297908727183920210.tmp\com\enjin\minecraft_commons\spigot\command\SpigotCommandCallerType.java:24: error: cannot find symbol
    [javac]         __CLR4_2_000jdfmfth8.R.inc(9);return !ObjectUtils.isNull(caller) && this.rawType.isAssignableFrom(caller.getClass());
    [javac]                                               ^
    [javac]   symbol:   variable ObjectUtils
    [javac]   location: class SpigotCommandCallerType
    [javac] 8 errors
:spigot:test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':spigot:test'.
> Compile failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED in 1s
9 actionable tasks: 7 executed, 2 up-to-date
Compile failed; see the compiler error output for details.
11:39:30 PM: Tasks execution finished 'clean install cloverGenerateReport'.
```

Stacktrace:
```
: Compile failed; see the compiler error output for details.
	at org.apache.tools.ant.taskdefs.Javac.compile(Javac.java:1181)
	at org.apache.tools.ant.taskdefs.Javac.execute(Javac.java:936)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
	at sun.reflect.GeneratedMethodAccessor256.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at groovy.util.AntBuilder.performTask(AntBuilder.java:327)
	at groovy.util.AntBuilder.nodeCompleted(AntBuilder.java:272)
	at groovy.util.BuilderSupport.doInvokeMethod(BuilderSupport.java:154)
	at groovy.util.AntBuilder.doInvokeMethod(AntBuilder.java:207)
	at groovy.util.BuilderSupport.invokeMethod(BuilderSupport.java:67)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:133)
	at com.bmuschko.gradle.clover.InstrumentCodeAction.compileJava(InstrumentCodeAction.groovy:332)
	at com.bmuschko.gradle.clover.InstrumentCodeAction.compileSrcFiles(InstrumentCodeAction.groovy:251)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:210)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:59)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:166)
	at com.bmuschko.gradle.clover.InstrumentCodeAction.compileClasses(InstrumentCodeAction.groovy:213)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:210)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:59)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:166)
	at com.bmuschko.gradle.clover.InstrumentCodeAction.instrumentCode(InstrumentCodeAction.groovy:135)
	at com.bmuschko.gradle.clover.InstrumentCodeAction.execute(InstrumentCodeAction.groovy:61)
	at com.bmuschko.gradle.clover.InstrumentCodeAction.execute(InstrumentCodeAction.groovy)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:711)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:694)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:122)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:317)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:309)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:185)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:95)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:111)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:70)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:88)
	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:242)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:317)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:309)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:185)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:95)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:235)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:224)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:121)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:77)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:102)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:96)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:612)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:567)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:96)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by Favorlock** [comment]
Problem solved, see original report for solution.
