### ISSUE TITLE
missing clover.license file in latest.

### ISSUE THREAD

**Issue by tinkerbell2018** [bmuschko/gradle-clover-plugin#120]
java.io.FileNotFoundException: java.io.FileNotFoundException: https://raw.githubusercontent.com/bmuschko/gradle-clover-plugin/master/clover.license
java.io.FileNotFoundException: https://raw.githubusercontent.com/bmuschko/gradle-clover-plugin/master/clover.license
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1836)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at java.net.URL.openStream(URL.java:1045)
	at com.bmuschko.gradle.clover.internal.LicenseUrlResolver.resolve(LicenseUrlResolver.groovy:30)
	at com.bmuschko.gradle.clover.internal.LicenseUrlResolverSpec.Resolve license from URL(LicenseUrlResolverSpec.groovy:63)

**Comment by Alex-Vol-SV** [comment]
First of all, you should not be referencing this file, it is only to be used by this open source product by our own builds. Not to be used by your builds.

Second, the clover.license is not required anymore. The plugin is now using the OpenClover library which has eliminated the need to use a clover.license file with the execution.
