### ISSUE TITLE
Using plugin with Grails 3

### ISSUE THREAD

**Issue by squarepegsys** [bmuschko/gradle-clover-plugin#71]
I'm trying to get this plugin to work with Grails 3. I'm sure I'm having a configuration problem, not a bug per se, but I'm lost

    apply plugin: 'com.bmuschko.clover'

    clover {
       licenseLocation ='license.txt'
       testIncludes = ["**/*Spec.groovy"]
       includes=["**/*.groovy"]
       additionalSourceDirs=["src/main/groovy", "grails-app"]
       additionalTestDirs=["src/integration-tests/groovy", "src/test/groovy"]
       report {
           html = true
           pdf = true
           xml = true
       }
     }

And this is the error I get:

    Caused by: groovy.lang.MissingMethodException: No signature of method:    java.lang.String.exists() is applicable for argument types: () values: []
    Possible solutions: wait(), next(), expand(), toList(), execute(), equals(java.lang.Object)
        at java_io_File$exists$0.call(Unknown Source)
        at com.bmuschko.gradle.clover.CloverPlugin$_addExistingSourceDirectories_closure51.doCall(CloverPlugin.groovy:356)
        at com.bmuschko.gradle.clover.CloverPlugin.addExistingSourceDirectories(CloverPlugin.groovy:355)
        at com.bmuschko.gradle.clover.CloverPlugin.this$2$addExistingSourceDirectories(CloverPlugin.groovy)

It seems to be `additionalSourceDirs` but I can't figure out what it really wants.

**Comment by bmuschko** [comment]
The type of property is [Set<File>](https://github.com/bmuschko/gradle-clover-plugin/blob/master/src/main/groovy/com/bmuschko/gradle/clover/CloverPluginConvention.groovy#L34). At the moment you are passing in a `List<String>`. It's not documented well. There should be Groovydocs for the plugin API.
